options:
    branch:
        default: release
        description: Installation type (release, nightly)
        type: string
    fms:
        default: true
        description: Enable fault-management-system
        type: boolean
    ase:
        default: true
        description: Enable autoscaling-engine
        type: boolean
    nse:
        default: true
        description: Enable network-slicing-engine
        type: boolean
    cli:
        default: true
        description: Enable openbaton-cli
        type: boolean
    monitoring_ip:
        default: localhost
        description: Reachable IP of the 
        type: string
